import { Colors } from "const"
import { Platform, Dimensions, StyleSheet } from "react-native"
import { scaleSize } from "styles/minixs"
import { RatioUtil } from "utils"
const { width, height } = Dimensions.get("window")

export const styles = StyleSheet.create({
    safeAreaView: {
        flex: 1,
        backgroundColor: Colors.WHITE,
    },
    mainView: {
        flex: 1,
        padding: RatioUtil.lengthFixedRatio(20),
        alignItems: "center",
    },
    backButton: {
        //...RatioUtil.sizeFixedRatio(8, 16),
        alignItems: "center",
        justifyContent: "center",
        left: RatioUtil.width(27),
        margin: 0,
        position: "absolute",
        ...RatioUtil.padding(20, 20, 20, 0),
    },
    headerView: {
        flexDirection: "row",
        height: scaleSize(50),
        width: RatioUtil.width(360),
        alignItems: "center",
        justifyContent: "space-between",
    },
    headerViewPurchase: {
        flexDirection: "row",
        height: RatioUtil.lengthFixedRatio(44),
        width: RatioUtil.width(360),
        alignItems: "center",
        justifyContent: "center",
    },
    footerView: {
        margin: RatioUtil.lengthFixedRatio(20),
    },
    backImage: {
        height: scaleSize(15),
        width: scaleSize(15),
    },
    headerTitleView: {
        height: RatioUtil.lengthFixedRatio(44),
        alignItems: "center",
        justifyContent: "center",
    },
    headerTitle: {
        fontSize: RatioUtil.font(16),
        fontWeight: RatioUtil.fontWeightBold(),
    },
    rectangleCard: {
        ...RatioUtil.sizeFixedRatio(109, 154),
        borderRadius: RatioUtil.width(5),
    },
    rectangleCardBox: {
        flexDirection: "row",
    },
    addRectangleCard: {
        borderWidth: 2,
        borderStyle: "dotted",
        borderColor: Colors.GRAY12,
        justifyContent: "center",
        alignItems: "center",
    },
    plus: {
        fontSize: scaleSize(30),
        color: Colors.GRAY12,
    },
    playerSelectionText: {
        fontSize: scaleSize(17),
        color: Colors.GRAY12,
        marginTop: scaleSize(5),
    },
    NFTChoiceCardTitle: {
        fontSize: RatioUtil.font(18),
        color: Colors.BLACK,
        marginTop: RatioUtil.lengthFixedRatio(16),
        fontWeight: RatioUtil.fontWeightBold(),
    },
    ratingsTitle: {
        fontSize: RatioUtil.font(13),
        color: Colors.GRAY8,
        marginRight: RatioUtil.width(3),
    },
    amountMainBox: {
        width: "100%",
        height: RatioUtil.lengthFixedRatio(60),
        backgroundColor: Colors.WHITE3,
        paddingHorizontal: RatioUtil.width(20),
        borderRadius: RatioUtil.width(10),
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginTop: RatioUtil.height(29),
    },
    amountBox: {
        flexDirection: "row",
        alignItems: "center",
    },
    amount: {
        color: Colors.BLACK,
        fontSize: RatioUtil.font(18),
        fontWeight: RatioUtil.fontWeightBold(),
    },
    coinIcon: {
        height: RatioUtil.width(16),
        width: RatioUtil.width(16),
        marginRight: RatioUtil.width(5),
    },
    policyMainBox: {
        width: "100%",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: RatioUtil.lengthFixedRatio(20),
    },
    policy: {
        fontSize: RatioUtil.font(13),
        fontWeight: "400",
    },
    policyImage: {
        height: RatioUtil.lengthFixedRatio(23),
        width: RatioUtil.lengthFixedRatio(23),
    },
    policyBox: {
        alignItems: "flex-end",
    },
    policyButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginTop: RatioUtil.lengthFixedRatio(10),
    },
    purchaseButton: {
        width: "100%",
        height: RatioUtil.lengthFixedRatio(60),
        borderRadius: RatioUtil.lengthFixedRatio(50),
        justifyContent: "center",
    },
    purchaseButtonTitle: {
        textAlign: "center",
        fontSize: RatioUtil.font(16),
        fontWeight: RatioUtil.fontWeightBold(),
    },
    checkbox: {
        borderRadius: scaleSize(20),
        marginRight: scaleSize(5),
    },
    centeredView: {
        backgroundColor: Colors.WHITE,
        width: width,
        borderTopEndRadius: scaleSize(20),
        borderTopStartRadius: scaleSize(20),
        padding: scaleSize(20),
        paddingBottom: scaleSize(150),
    },
    modalView: {
        backgroundColor: Colors.GRAY,
        flex: 1,
    },
    playerSelectionTitle: {
        fontSize: scaleSize(18.5),
        color: Colors.BLACK,
        fontWeight: "600",
        textAlign: "center",
    },
    playerSelectionDescription: {
        fontSize: scaleSize(16),
        color: Colors.GRAY8,
        fontWeight: "600",
        textAlign: "center",
        marginTop: scaleSize(10),
    },
    backgroundStyle: {
        backgroundColor: Colors.WHITE,
        borderRadius: scaleSize(10),
        flexDirection: "row",
        paddingHorizontal: 15,
        width: "100%",
        alignSelf: "flex-start",
        padding: scaleSize(20),
        borderWidth: scaleSize(1),
        borderColor: Colors.GRAY7,
        marginTop: scaleSize(20),
    },
    inputStyle: {
        fontSize: 16,
        flex: 1,
        paddingLeft: 5,
    },
    iconStyle: {
        alignSelf: "center",
        height: scaleSize(20),
        width: scaleSize(20),
        marginRight: scaleSize(5),
    },
    imageBox: {
        flex: 1,
        marginVertical: scaleSize(20),
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
    },
    image: {
        width: width / 3 - 20,
        height: scaleSize(150),
        backgroundColor: Colors.GRAY7,
        marginVertical: 5,
        borderRadius: scaleSize(10),
    },
    playerImage: {
        flex: 1,
    },
    outSideButton: {
        height: scaleSize(50),
    },
    button: {
        width: "90%",
        padding: scaleSize(20),
        borderRadius: scaleSize(30),
        position: "absolute",
        bottom: scaleSize(30),
        zIndex: 100,
        alignSelf: "center",
        alignItems: "center",
    },
    selectionModal: {
        flex: 1,
        backgroundColor: `${Colors.BLACK}70`,
        alignItems: "center",
        justifyContent: "center",
    },
    selectionModalInner: {
        backgroundColor: Colors.WHITE,
        alignItems: "center",
        padding: RatioUtil.lengthFixedRatio(20),
        borderRadius: RatioUtil.lengthFixedRatio(16),
        width: RatioUtil.width(272),
    },
    selectionModalInnerTitle: {
        fontSize: RatioUtil.font(18),
        height: RatioUtil.lengthFixedRatio(27),
        fontWeight: RatioUtil.fontWeightBold(),
        color: Colors.BLACK,
        marginTop: RatioUtil.lengthFixedRatio(10),
    },
    selectionModalInnerDesc: {
        fontSize: RatioUtil.font(14),
        fontWeight: RatioUtil.fontWeightBold(),
        color: Colors.BLACK,
        marginTop: RatioUtil.lengthFixedRatio(20),
        marginBottom: RatioUtil.lengthFixedRatio(6),
    },
    drawModalMainView: {
        // backgroundColor: 'pink'
        alignItems: "center",
    },
    drawModalInnerView: {
        height: RatioUtil.lengthFixedRatio(40),
        width: RatioUtil.width(232),
        flexDirection: "row",
        marginTop: RatioUtil.lengthFixedRatio(4),
        alignItems: "center",
        justifyContent: "space-between",
        borderRadius: scaleSize(5),
        paddingHorizontal: scaleSize(15),
    },
    drawtitle: {
        fontSize: RatioUtil.font(14),
        color: Colors.BLACK,
    },
    drawProgress: {
        fontSize: RatioUtil.font(14),
        fontWeight: RatioUtil.fontWeightBold(),
        color: Colors.BLACK,
    },
    modalButtonView: {
        height: RatioUtil.lengthFixedRatio(48),
        width: "100%",
        backgroundColor: Colors.BLACK,
        borderRadius: RatioUtil.lengthFixedRatio(100),
        alignItems: "center",
        justifyContent: "center",
        marginTop: RatioUtil.lengthFixedRatio(30),
    },
    modalButtonText: {
        fontSize: RatioUtil.font(14),
        fontWeight: RatioUtil.fontWeightBold(),
        color: Colors.WHITE,
    },
    selectedImage: {
        height: RatioUtil.lengthFixedRatio(50),
        width: RatioUtil.width(50),
        marginTop: RatioUtil.lengthFixedRatio(10),
    },
    checkImage: {
        height: scaleSize(25),
        width: scaleSize(25),
    },
    modalTitle: {
        fontSize: scaleSize(16),
        lineHeight: scaleSize(18),
        fontWeight: "900",
        color: Colors.BLACK,
    },
    modalDesc: {
        fontSize: scaleSize(13),
        lineHeight: scaleSize(18),
        fontWeight: "500",
        color: Colors.GRAY3,
        width: scaleSize(175),
        textAlign: "center",
        marginTop: scaleSize(10),
    },
    completeTitle: {
        fontSize: RatioUtil.font(16),
        color: Colors.BLACK3,
        marginVertical: RatioUtil.lengthFixedRatio(10),
        textAlign: "center",
        width: "100%",
    },
    completeDesc: {
        fontSize: RatioUtil.font(14),
        lineHeight: RatioUtil.font(14) * 1.4,
        color: Colors.BLACK,
        textAlign: "center",
        width: "100%",
    },
    typeModal: {
        height: scaleSize(40),
        width: "100%",
        backgroundColor: Colors.BLACK,
        marginTop: scaleSize(10),
        borderRadius: scaleSize(5),
        alignItems: "center",
        justifyContent: "center",
    },
    typeModalText: {
        fontSize: scaleSize(12),
        lineHeight: scaleSize(14),
        fontWeight: "700",
        color: Colors.WHITE,
    },
})
