import { PixelRatio, StyleSheet } from "react-native"
import { Colors, Dimension } from "const"
import { RatioUtil } from "utils"

export const liveStyle = {
    tabMenu: StyleSheet.create({
        con: {
            backgroundColor: Colors.WHITE,
            //borderBottomWidth: 1,
            //borderBottomColor: Colors.GRAY7,
            elevation: 0,
            height: RatioUtil.height(48),
            justifyContent: "center",
        },
        title: {
            color: Colors.GRAY3,
            fontSize: RatioUtil.font(14),
            width: RatioUtil.width(60),
            fontWeight: RatioUtil.fontWeightBold(),
            alignSelf: "center",
            textAlign: "center",
            //marginTop: RatioUtil.lengthFixedRatio(7),
        },
        indicator: {
            backgroundColor: Colors.BLACK,
            borderLeftColor: Colors.WHITE,
            borderRightColor: Colors.WHITE,
            height: RatioUtil.lengthFixedRatio(2),
            marginBottom: RatioUtil.lengthFixedRatio(-1),
            borderRadius: RatioUtil.width(100),
        },
    }),
    cheerTab: StyleSheet.create({
        rankBox: {
            ...RatioUtil.size(360, 40),
            alignItems: "center",
            justifyContent: "flex-start",
            backgroundColor: Colors.WHITE,
            ...RatioUtil.borderRadius(0, 0, 10, 10),
            elevation: 3,
            shadowColor: "gba(0, 0, 0, 0.12)",
            shadowOpacity: 0.5,
            shadowRadius: 5,
            shadowOffset: {
                height: 4,
                width: 4,
            },
            flexDirection: "row",
            ...RatioUtil.padding(12, 20, 12, 20),
            position: "absolute",
            zIndex: 1,
            zPosition: 1,
        },
        rank: {
            flexDirection: "row",
            paddingRight: RatioUtil.width(12),
            // borderRightWidth: 1,
            // borderColor: Colors.GRAY,
            alignItems: "center",
            // paddingBottom: RatioUtil.height(0.5),
            height: RatioUtil.height(16),
        },
        rankImg: {
            marginRight: RatioUtil.width(2),
            ...RatioUtil.size(16, 16),
        },
        rankName: {
            color: Colors.BLACK,
            fontSize: RatioUtil.font(12),
            fontWeight: "600",
        },
        rankPoint: {
            fontSize: RatioUtil.font(12),
            fontWeight: "400",
            marginLeft: RatioUtil.width(9),
        },
        chatCon: {
            flex: 1,
            backgroundColor: Colors.WHITE,

            // minHeight: RatioUtil.height(100),
            // height: RatioUtil.height(323),
            paddingLeft: RatioUtil.width(20),
            paddingRight: RatioUtil.width(20),
            //marginBottom: RatioUtil.height(35),
        },
        chatName: {
            fontSize: RatioUtil.font(12),
            fontWeight: "400",
            marginRight: RatioUtil.width(4),
            color: Colors.BLACK,
        },
        chatContents: {
            fontSize: RatioUtil.font(14),
            fontWeight: "400",
            marginRight: RatioUtil.width(5),
            color: Colors.BLACK,
        },
        chatDeclare: {
            fontSize: RatioUtil.font(14),
            fontWeight: "400",
            marginRight: RatioUtil.width(5),
            color: Colors.RED2,
        },
        chatDate: {
            fontSize: RatioUtil.font(12),
            fontWeight: "400",
            color: Colors.GRAY3,
        },
        chatInputCon: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
        },
        chatInput: {
            fontSize: RatioUtil.font(13),
            ...RatioUtil.paddingFixedRatio(11, 72, 11, 10),
            color: Colors.BLACK,
            borderWidth: 1,
            borderRadius: RatioUtil.width(5),
            borderColor: Colors.GRAY,
        },
        heartCon: {
            ...RatioUtil.size(48, 48),
            marginLeft: RatioUtil.width(10),
            borderWidth: 1,
            alignItems: "center",
            justifyContent: "center",
            borderRadius: RatioUtil.width(24),
            borderColor: Colors.GRAY,
        },

        heartMsgCon: {
            backgroundColor: Colors.PURPLE2,
            ...RatioUtil.sizeFixedRatio(320, 32),
            textAlign: "center",
            position: "absolute",
            bottom: RatioUtil.height(52),
            zIndex: 1,
            elevation: 1,
            alignSelf: "center",
            justifyContent: "center",
            alignItems: "center",
            ...RatioUtil.borderRadius(20, 20, 20, 20),
            flexDirection: "row",
        },
        heartClose: {
            marginRight: RatioUtil.width(3),
        },
        heartAngle: {
            position: "absolute",
            // zIndex: 2,
            // elevation: 2,
            ...RatioUtil.sizeFixedRatio(10.39, 9),
            right: RatioUtil.width(19.8),
            bottom: RatioUtil.height(-4),
        },
        heartMsg: {
            color: Colors.PURPLE,
            fontSize: RatioUtil.font(12),
            fontWeight: "700",
        },
        money: {
            ...RatioUtil.size(30, 30),
            position: "absolute",
            // left: RatioUtil.width(225),
            alignItems: "center",
            justifyContent: "center",
        },
        sendIcon: {
            position: "absolute",
            // left: RatioUtil.width(195),
            ...RatioUtil.size(30, 30),
            alignItems: "center",
            justifyContent: "center",
            top: "18%",
        },
        errorCon: {
            ...RatioUtil.size(340, 30),
            position: "absolute",
            backgroundColor: "rgba(0, 0, 0, 0.5)",
            bottom: RatioUtil.height(40),
            alignItems: "center",
            alignSelf: "center",
            justifyContent: "center",
            ...RatioUtil.borderRadius(20, 20, 20, 20),
        },
        errorMsg: {
            color: Colors.WHITE,
            fontSize: RatioUtil.font(12),
        },
        playerCon: {
            flexDirection: "row",
            justifyContent: "space-between",
            width: RatioUtil.width(322),
            position: "absolute",
            bottom: RatioUtil.height(68),
            alignSelf: "center",
            alignItems: "center",
        },
    }),
    liveTab: StyleSheet.create({
        con: {
            flex: 1,
            backgroundColor: Colors.WHITE,
        },
        title: {
            color: Colors.BLACK,
            fontSize: RatioUtil.font(18),
            fontWeight: "600",
        },
        subTitle: {
            color: Colors.GRAY8,
            fontSize: RatioUtil.font(12),
            fontWeight: "400",
        },
        infoCon: {
            marginVertical: RatioUtil.height(10),
            backgroundColor: Colors.PURPLE2,
            padding: RatioUtil.width(10),
        },
        infoChildCon: {
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            paddingBottom: RatioUtil.width(10),
        },
        textInfo: {
            color: Colors.BLACK,
            fontSize: RatioUtil.font(16),
            fontWeight: "600",
        },
        imageInfo: {
            ...RatioUtil.size(15, 15),
            marginLeft: RatioUtil.width(5),
        },
        imageCoin: {
            ...RatioUtil.size(15, 15),
            marginRight: RatioUtil.width(5),
        },
        percentCon: {
            paddingTop: RatioUtil.width(5),
        },
        textPercent: {
            color: Colors.PURPLE4,
            fontSize: RatioUtil.font(12),
            fontWeight: "600",
        },
        btnReceive: {
            backgroundColor: Colors.WHITE,
            borderColor: Colors.GRAY13,
            borderWidth: 1,
            alignItems: "center",
            justifyContent: "center",
            width: RatioUtil.width(70),
            height: RatioUtil.height(40),
            borderRadius: RatioUtil.width(100),
        },
        textBtnReceive: {
            color: Colors.GRAY13,
            fontSize: RatioUtil.font(14),
            fontWeight: "600",
        },
        flexBetween: { display: "flex", flexDirection: "row", justifyContent: "space-between" },
        vodCon: {
            paddingHorizontal: RatioUtil.width(10),
            paddingBottom: RatioUtil.width(10),
        },
        textCountVod: {
            color: Colors.GRAY14,
            fontSize: RatioUtil.font(16),
            fontWeight: "600",
        },
        videoTitle: {
            color: Colors.BLACK,
            fontSize: RatioUtil.font(14),
            fontWeight: "400",
        },
    }),
    nftTab: StyleSheet.create({
        toggleCon: {
            ...RatioUtil.size(360, 160),
            backgroundColor: Colors.WHITE,
            alignItems: "center",
        },
        toggleCons: {
            ...RatioUtil.size(360, 80),
            backgroundColor: Colors.WHITE,
            alignItems: "center",
        },
        toggleBox: {
            ...RatioUtil.sizeFixedRatio(248, 40),
            borderRadius: 100,
            borderColor: Colors.GRAY13,
            borderWidth: 1,
            marginTop: RatioUtil.lengthFixedRatio(20),
            flexDirection: "row",
            justifyContent: "center",
            alignItems: "center",
        },

        toggles: {
            ...RatioUtil.sizeFixedRatio(120, 32),
            borderRadius: 1000,
            backgroundColor: Colors.BLACK,
            justifyContent: "center",
        },
        toggle: {
            ...RatioUtil.sizeFixedRatio(120, 32),
            borderRadius: 100,
            justifyContent: "center",
        },
        toggleTexts: {
            fontWeight: "bold",
            fontSize: RatioUtil.font(14),
            lineHeight: RatioUtil.font(14) * 1.3,
            textAlign: "center",
            color: Colors.WHITE,
        },
        toggleText: {
            fontWeight: "bold",
            fontSize: RatioUtil.font(14),
            lineHeight: RatioUtil.font(14) * 1.3,
            textAlign: "center",
            color: Colors.GRAY3,
        },
        guideBox: {
            ...RatioUtil.size(320, 60),
            borderRadius: 8,
            // backgroundColor: Colors.GRAY9,
            marginTop: RatioUtil.lengthFixedRatio(20),
            justifyContent: "center",
            alignItems: "center",
            marginBottom: RatioUtil.lengthFixedRatio(20),
        },
        guideTextBox: { ...RatioUtil.sizeFixedRatio(320, 40), justifyContent: "center", alignItems: "center" },
        guideText: {
            fontWeight: "normal",
            fontSize: RatioUtil.font(13),
            lineHeight: RatioUtil.font(13) * 1.3,
            textAlign: "center",
            color: Colors.GRAY8,
        },
        nftCon: {
            ...RatioUtil.size(360, 80),
            backgroundColor: Colors.WHITE,
            flexDirection: "row",
            alignItems: "center",
        },
        nftLv: {
            position: "absolute",
            ...RatioUtil.size(28, 18),
            left: RatioUtil.width(14),
            justifyContent: "center",
            alignItems: "center",
        },
        nftText: {
            fontSize: RatioUtil.font(14),
            fontWeight: "600",
            lineHeight: 18.2,
            color: Colors.BLACK,
        },
        nftText2: {
            paddingTop: RatioUtil.height(6),
            fontSize: RatioUtil.font(16),
            fontWeight: "600",
            lineHeight: 20.8,
            color: Colors.BLACK,
        },
        nftText3: {
            fontSize: RatioUtil.font(14),
            fontWeight: "400",
            lineHeight: 18.2,
            color: Colors.GRAY3,
        },
        nftImgBox: {
            ...RatioUtil.size(50, 50),
            borderRadius: 1000,
            borderWidth: 1,
            borderColor: Colors.GRAY13,
            left: RatioUtil.width(52),
            position: "absolute",
            overflow: "hidden",
        },
        nftName: { left: RatioUtil.width(122), position: "absolute" },
        nftHit: { alignItems: "center", left: RatioUtil.width(220), width: RatioUtil.width(60), position: "absolute" },
        nftToken: {
            justifyContent: "center",
            alignItems: "center",
            width: RatioUtil.width(60),
            position: "absolute",
            left: RatioUtil.width(280),
        },
        dropCon: {
            // ...RatioUtil.size(360, 404),
            padding: RatioUtil.width(25),
            backgroundColor: Colors.GRAY9,
        },
        dropTop: {
            // ...RatioUtil.size(360, 168),
            display: "flex",
            flexDirection: "row",
        },
        dropNftCard: {
            ...RatioUtil.size(82, 100),
            backgroundColor: Colors.RED3,
            borderRadius: 5,
            // position: "absolute",
            // left: RatioUtil.width(20),
            // top: RatioUtil.height(20),
        },
        dropTopTitleBox: {
            // ...RatioUtil.size(135, 21),
            // position: "absolute",
            // left: RatioUtil.width(122),
            // top: RatioUtil.height(29),
            display: "flex",
            flexDirection: "row",
        },
        dropTopTitle: {
            color: Colors.BLACK,
            fontSize: RatioUtil.font(16),
            fontWeight: "400",
            // lineHeight: RatioUtil.height(20.8),
        },
        dropTopRound: {
            ...RatioUtil.size(20, 20),
            position: "absolute",
            top: RatioUtil.height(64),
            left: RatioUtil.width(122),
        },
        dropTopRoundText: {
            // position: "absolute",
            fontSize: RatioUtil.font(14),
            fontWeight: "400",
            // lineHeight: 18.2,
            color: Colors.BLACK,
        },
        dropTopRoundbtn: {
            ...RatioUtil.size(19, 28),
            top: RatioUtil.height(140),
            left: RatioUtil.width(20),
            position: "absolute",
        },
        dropTopRoundbtnTexts: {
            fontSize: RatioUtil.font(14),
            fontWeight: "600",
            lineHeight: 18.2,
            color: Colors.BLACK,
        },
        dropTopRoundbtnText: {
            fontSize: RatioUtil.font(14),
            fontWeight: "600",
            lineHeight: 18.2,
            color: Colors.GRAY8,
        },
        dropTopsBar: {
            ...RatioUtil.size(19, 2),
            backgroundColor: Colors.BLACK,
            borderRadius: 15,
            position: "absolute",
            bottom: 0,
        },
        dropTopRight: {
            paddingLeft: RatioUtil.width(10),
            justifyContent: "center",
        },
        roundsInfoCon: {
            display: "flex",
            flexDirection: "row",
            flexWrap: "wrap",
            paddingRight: RatioUtil.width(25),
        },
        roundInfoCon: {
            display: "flex",
            flexDirection: "row",
            width: "50%",
            paddingTop: RatioUtil.height(10),
        },
        roundIconCon: {
            backgroundColor: Colors.GRAY10,
            borderRadius: RatioUtil.width(10),
            overflow: "hidden",
            ...RatioUtil.size(20, 20),
            justifyContent: "center",
            alignItems: "center",
        },
        textRoundIcon: {
            color: Colors.WHITE,
            fontWeight: "600",
            fontSize: RatioUtil.font(12),
            textAlign: "center",
        },
        roundTabCon: {
            marginTop: RatioUtil.height(10),
        },
        roundText: {
            borderBottomWidth: 0,
            borderColor: Colors.WHITE,
            paddingVertical: RatioUtil.height(5),
            color: Colors.GRAY8,
            fontSize: RatioUtil.font(14),
            fontWeight: "600",
        },
        totalCon: {
            width: "15%",
            paddingVertical: RatioUtil.width(10),
            borderColor: Colors.BLACK,
            borderTopWidth: 0.5,
            borderRightWidth: 0.5,
        },
        scoreTextCon: {
            width: "100%",
            height: RatioUtil.width(40),
            justifyContent: "center",
        },
        scoreText: {
            fontSize: RatioUtil.font(12),
            color: Colors.BLACK,
            textAlign: "center",
        },
        rightBorder: {
            borderColor: Colors.BLACK,
            borderRightWidth: 0.5,
        },
        topBorder: {
            borderColor: Colors.BLACK,
            borderTopWidth: 0.5,
        },
        topBottomBorder: {
            borderColor: Colors.BLACK,
            borderTopWidth: 0.5,
            borderBottomWidth: 0.5,
        },
        colorCon: {
            marginRight: RatioUtil.width(10),
            alignItems: "center",
            flexDirection: "row",
        },
        itemColor: {
            ...RatioUtil.size(10, 10),
            borderRadius: RatioUtil.width(5),
            marginRight: RatioUtil.width(2),
        },
        textColor: {
            fontSize: RatioUtil.font(12),
            fontWeight: "400",
            color: "#9B9BA3",
        },
        tbdCon: {
            ...RatioUtil.size(100, 100),
            backgroundColor: Colors.GRAY12,
            justifyContent: "center",
            alignItems: "center",
        },
        textTbd: {
            fontWeight: "400",
            fontSize: RatioUtil.font(14),
            color: Colors.WHITE,
        },
        buttonNavigationCon: {
            marginTop: RatioUtil.width(10),
            backgroundColor: Colors.GRAY7,
            borderRadius: RatioUtil.width(100),
            height: RatioUtil.lengthFixedRatio(40),
            alignContent: "center",
            alignItems: "center",
            ...RatioUtil.paddingFixedRatio(10, 20, 10, 20),
        },
    }),
}

export const liveCompoStyle = {
    confirm: StyleSheet.create({
        con: {
            ...RatioUtil.size(272, 393),
            ...RatioUtil.padding(30, 22, 20, 22),
            backgroundColor: Colors.WHITE,
            alignSelf: "center",
            alignItems: "center",
            justifyContent: "center",
            ...RatioUtil.borderRadius(20),
        },
        title: {
            fontSize: RatioUtil.font(15),
            color: Colors.BLACK,
            textAlign: "center",
        },
        checkBox: {
            //hazel 수정
            // ...RatioUtil.margin(12, 0, 22, 0),
            ...RatioUtil.margin(12, 20, 22, 20),
        },
        checkBoxText: {
            marginLeft: RatioUtil.width(6),
            fontSize: RatioUtil.font(14),
            color: Colors.BLACK,
        },

        warningCon: {
            ...RatioUtil.size(232, 177),
            backgroundColor: Colors.GRAY9,
            ...RatioUtil.padding(20, 7, 20, 20),
            borderWidth: 1,
            ...RatioUtil.borderRadius(6),
            borderColor: Colors.GRAY7,
        },
        warningTitle: {
            color: Colors.BLACK,
            fontSize: RatioUtil.font(12),
        },
        warningText: {
            fontSize: RatioUtil.font(12),
            lineHeight: RatioUtil.font(12) * 1.4,
            color: Colors.GRAY8,
            marginTop: RatioUtil.height(6),
        },
        warningBtn: {
            ...RatioUtil.size(113, 48),
            ...RatioUtil.borderRadius(30),
            justifyContent: "center",
            alignItems: "center",
            marginTop: RatioUtil.height(20),
        },
        warningBtnText: {
            fontSize: RatioUtil.font(14),
            fontWeight: "600",
        },
    }),
    proSelect: StyleSheet.create({}),
}

export const liveGeneral = {
    popup: StyleSheet.create({
        title: {
            fontWeight: RatioUtil.fontWeightBold(),
            fontSize: RatioUtil.font(18),
            color: Colors.BLACK,
        },
        center: {
            alignItems: "center",
            justifyContent: "center",
        },
        viewRow: {
            ...RatioUtil.size(360, 170),
            padding: RatioUtil.width(20),
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
        },
        container: {
            height: RatioUtil.height(110),
            borderRadius: RatioUtil.width(10),
            backgroundColor: Colors.GRAY9,
            overflow: "hidden",
        },
        txtUserName: {
            ...RatioUtil.padding(0, 0, 10, 0),
            flex: 1,
            alignItems: "center",
            justifyContent: "flex-end",
        },
        icon: {
            position: "absolute",
            top: -RatioUtil.width(10),
            left: RatioUtil.width(32),
            ...RatioUtil.size(33, 33),
        },
        rankListItem: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignSelf: "center",
            marginBottom: RatioUtil.height(10),
            ...RatioUtil.padding(9, 20, 9, 20),
            ...RatioUtil.size(320, 48),
            backgroundColor: Colors.GRAY9,
        },
    }),
}

export const cheerStyle = {
    donatePopup: StyleSheet.create({
        con: {
            backgroundColor: Colors.WHITE,
            position: "absolute",
            width: RatioUtil.width(360),
            borderTopLeftRadius: RatioUtil.width(16),
            borderTopRightRadius: RatioUtil.width(16),
        },
        errCon: {
            marginLeft: RatioUtil.width(10),
            flexDirection: "row",
            alignItems: "center",
            marginTop: RatioUtil.height(9),
        },
        errMsg: {
            marginLeft: RatioUtil.width(6),
            color: Colors.RED2,
        },
        inputLength: {
            position: "absolute",
            right: RatioUtil.width(10),
            fontSize: RatioUtil.font(14),
            fontWeight: "400",
            lineHeight: RatioUtil.font(14) * 1.4,
            color: Colors.GRAY3,
            bottom: 5,
        },
        input: {
            paddingLeft: RatioUtil.width(10),
            borderBottomLeftRadius: RatioUtil.width(8),
            borderBottomRightRadius: RatioUtil.width(8),
        },
        headerTitle: {
            fontWeight: RatioUtil.fontWeightBold(),
            fontSize: RatioUtil.font(18),
            color: Colors.BLACK,
            textAlign: "center",
        },
        infoCon: {
            //marginTop: RatioUtil.height(10),
            borderTopLeftRadius: RatioUtil.width(8),
            borderTopRightRadius: RatioUtil.width(8),
            width: RatioUtil.lengthFixedRatio(320),
            height: RatioUtil.lengthFixedRatio(48),
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        infoLeftCon: {
            display: "flex",
            flexDirection: "row",
            justifyContent: "center",
            alignItems: "center",
            marginLeft: RatioUtil.lengthFixedRatio(20),
        },
        infoText: {
            fontWeight: "700",
            fontSize: RatioUtil.font(16),
            color: Colors.WHITE,
        },
        wCon: {
            backgroundColor: "transparent",
            borderColor: Colors.WHITE,
            borderWidth: 2,
            height: RatioUtil.lengthFixedRatio(23),
            borderRadius: RatioUtil.width(30),
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            marginRight: RatioUtil.lengthFixedRatio(20),
        },
        coinCon: {
            backgroundColor: "transparent",
            marginLeft: RatioUtil.lengthFixedRatio(5),
            marginRight: RatioUtil.lengthFixedRatio(8),
            height: RatioUtil.height(16),
            alignItems: "center",
            justifyContent: "center",
        },
        thumb: {
            borderColor: Colors.WHITE,
            borderRadius: RatioUtil.width(27),
            borderWidth: 5.5,
            height: RatioUtil.width(27),
            shadowColor: "#000",
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
            width: RatioUtil.width(27),
        },
        track: {
            backgroundColor: Colors.GRAY9,
            borderRadius: 4,
            height: RatioUtil.height(10),
            shadowColor: Colors.BLACK,
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.15,
            shadowRadius: 1,
        },
        groupButtonCon: {
            marginTop: RatioUtil.lengthFixedRatio(25),
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            marginBottom: RatioUtil.lengthFixedRatio(20),
        },
        buttonCon: {
            ...RatioUtil.size(150, 50),
            alignItems: "center",
            justifyContent: "center",
            borderRadius: 30,
            ...RatioUtil.margin(14, 0, 15, 0),
        },
        buttonKeyboard: {
            ...RatioUtil.size(360, 50),
            ...RatioUtil.margin(0, 0, 0, 0),
            alignItems: "center",
            justifyContent: "center",
        },
        buttonTitle: {
            fontWeight: "600",
            fontSize: RatioUtil.font(16),
        },
    }),
}
