import { PixelRatio, Platform, StyleSheet } from "react-native"
import { Colors } from "const"
import { RatioUtil } from "utils"

export const mineStyle = {
    myPage: StyleSheet.create({
        header: {
            backgroundColor: Colors.WHITE,
            // width: RatioUtil.width(360),
            // height: RatioUtil.height(44),
            ...RatioUtil.size(360, 44),
            alignItems: "center",
            justifyContent: "center",
        },
        headerText: {
            fontWeight: "600",
            fontSize: RatioUtil.font(16),
            lineHeight: RatioUtil.font(16) * 1.4,
            color: Colors.BLACK,
        },
        ProfileCon: {
            backgroundColor: Colors.WHITE,
            // width: RatioUtil.width(360),
            // height: RatioUtil.height(140),
            ...RatioUtil.size(360, 140),
            flexDirection: "row",
            // paddingVertical: RatioUtil.height(30),
            // paddingLeft: RatioUtil.width(20),
            // paddingRight: RatioUtil.width(28),
            ...RatioUtil.padding(30, 0, 0, 20),
        },
        profileButtonCon: {
            position: "absolute",
            top: RatioUtil.height(28),
            right: RatioUtil.width(20),
            zIndex: 1,
            backgroundColor: Colors.GRAY7,
            // borderRadius: RatioUtil.width(14),
            // width: RatioUtil.width(73),
            // height: RatioUtil.height(28),
            ...RatioUtil.size(73, 28),
            ...RatioUtil.borderRadius(14),
            alignItems: "center",
            justifyContent: "center",
        },
        profileButtonText: {
            fontSize: RatioUtil.font(12),
            fontWeight: "600",
            lineHeight: RatioUtil.font(12) * 1.42,
            letterSpacing: RatioUtil.font(12) * -0.04,
            color: Colors.BLACK,
        },
        titleText: {
            fontSize: RatioUtil.font(18),
            fontWeight: "700",
            lineHeight: RatioUtil.font(18) * 1.2,
            color: Colors.BLACK,
        },
        greetText: {
            width: RatioUtil.width(212),
            fontSize: RatioUtil.font(14),
            fontWeight: "400",
            lineHeight: RatioUtil.font(14) * 1.45,
            color: Colors.GRAY2,
            // marginTop: RatioUtil.height(10),
            ...RatioUtil.margin(10),
        },
        menuCon: {
            // width: RatioUtil.width(360),
            // height: RatioUtil.height(472),
            ...RatioUtil.size(360, 472),
            // marginTop: RatioUtil.height(3),
            //...RatioUtil.margin(3),
            backgroundColor: Colors.WHITE,
            // paddingHorizontal: RatioUtil.width(20),
            // paddingTop: RatioUtil.height(30),
            ...RatioUtil.padding(30, 20, 0, 20),
        },
        menuText: {
            fontSize: RatioUtil.font(14),
            fontWeight: "700",
            //lineHeight: RatioUtil.font(14) * 1.4,
            color: Colors.BLACK2,
        },
        linkCon: {
            // width: RatioUtil.width(320),
            // height: RatioUtil.height(107),
            ...RatioUtil.size(360, 90),
            ...RatioUtil.margin(20, 0, 20, 0),
            // marginTop: RatioUtil.height(20),
        },
        linkTitleText: {
            fontSize: RatioUtil.font(16),
            fontWeight: "700",
            lineHeight: RatioUtil.font(16) * 1.5,
            color: Colors.GRAY3,
        },
        linkButtonCon: {
            minWidth: RatioUtil.width(46),
            height: RatioUtil.height(72),
            alignItems: "center",
            justifyContent: "center",
        },
        linkIcon: {
            // width: RatioUtil.width(146),
            // height: RatioUtil.height(146),
            ...RatioUtil.size(46, 46),
            backgroundColor: Colors.GRAY9,
            // borderRadius: 73,
            ...RatioUtil.borderRadius(23),
            borderWidth: 1,
            borderColor: Colors.GRAY7,
            alignItems: "center",
            justifyContent: "center",
            // marginBottom: RatioUtil.height(9),
            ...RatioUtil.margin(0, 0, 9, 0),
        },
        linkText: {
            textAlign: "center",
            fontSize: RatioUtil.font(12),
            fontWeight: "400",
            lineHeight: RatioUtil.font(12) * 1.4,
            color: Colors.GRAY2,
        },
    }),

    edit: StyleSheet.create({
        titleCon: {
            backgroundColor: Colors.WHITE,
            alignItems: "center",
            // flex: 1,
            // paddingTop: RatioUtil.height(30),
            // paddingHorizontal: RatioUtil.width(20),
            ...RatioUtil.padding(30, 20, 0, 20),
        },
        profileButtonCon: {
            // width: RatioUtil.width(92),
            // height: RatioUtil.width(92),
            ...RatioUtil.size(92, 92),
            // paddingLeft: RatioUtil.width(10),
            marginRight: 0,
        },
        profileButtonImg: {
            // width: RatioUtil.width(92),
            // height: RatioUtil.height(92),
            ...RatioUtil.size(92, 92),
        },
        profileButtonIcon: {
            bottom: RatioUtil.height(1),
            // width: RatioUtil.width(27),
            // height: RatioUtil.height(27),
            ...RatioUtil.size(27, 27),
            right: RatioUtil.width(3),
        },

        inputCon: {
            width: RatioUtil.width(320),
            // height: RatioUtil.height(98),
            // ...RatioUtil.size(320, 98),
            // marginTop: RatioUtil.height(40),
            ...RatioUtil.margin(40),
        },
        inputTitle: {
            fontSize: RatioUtil.font(14),
            fontWeight: "600",
            lineHeight: RatioUtil.font(14) * 1.4,
            color: Colors.BLACK,
            // marginLeft: RatioUtil.width(10),
        },
        inputLength: {
            position: "absolute",
            // top: RatioUtil.height(39),
            right: RatioUtil.width(10),
            fontSize: RatioUtil.font(14),
            fontWeight: "400",
            lineHeight: RatioUtil.font(14) * 1.4,
            color: Colors.GRAY3,
        },
        input: {
            paddingLeft: RatioUtil.width(10),
            borderRadius: RatioUtil.width(8),

            marginTop: RatioUtil.height(4),
        },
        errCon: {
            marginLeft: RatioUtil.width(10),
            flexDirection: "row",
            alignItems: "center",
            marginTop: RatioUtil.height(9),
        },
        errMsg: {
            marginLeft: RatioUtil.width(6),
            color: Colors.RED2,
        },
        saveButtonCon: {
            // width: RatioUtil.width(320),
            // height: RatioUtil.height(60),
            ...RatioUtil.size(320, 60),
            alignItems: "center",
            justifyContent: "center",
            borderRadius: 30,
            // marginTop: RatioUtil.height(14),
            // marginBottom: RatioUtil.height(122),
            ...RatioUtil.margin(14, 0, 122, 0),
        },
        saveButtonTitle: {
            fontWeight: "700",
            fontSize: RatioUtil.font(16),
        },
    }),

    record: StyleSheet.create({
        listCon: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            width: RatioUtil.width(360),
            height: RatioUtil.height(60),
            paddingHorizontal: RatioUtil.width(20),
        },
        emptyListCon: {
            width: RatioUtil.width(360),
            height: RatioUtil.height(120),
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: Colors.GRAY9,
        },
        listTitleText: {
            fontSize: RatioUtil.font(13),
            fontWeight: "400",
            lineHeight: RatioUtil.font(13) * 1.4,
            letterSpacing: RatioUtil.font(13) * -0.02,
            color: Colors.GRAY3,
        },
        dataCon: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            width: RatioUtil.width(320),
            height: RatioUtil.height(40),
            marginTop: RatioUtil.height(20),
        },
        icon: {
            width: RatioUtil.width(40),
            height: RatioUtil.width(40),
            borderRadius: RatioUtil.width(12),
            borderColor: Colors.GRAY7,
            borderWidth: 1,
            backgroundColor: Colors.WHITE,
            marginRight: RatioUtil.width(10),
            alignItems: "center",
            justifyContent: "center",
        },
        valueText: {
            fontSize: RatioUtil.font(14),
            fontWeight: "600",
            lineHeight: RatioUtil.font(14) * 1.4,
            textAlign: "right",
            color: Colors.BLACK,
        },
        typeText: {
            fontSize: RatioUtil.font(12),
            fontWeight: "600",
            lineHeight: RatioUtil.font(12) * 1.4,
            textAlign: "right",
            color: Colors.GRAY3,
        },
        emptyIcon: {
            width: RatioUtil.width(75),
            height: RatioUtil.height(75),
            borderRadius: RatioUtil.width(12),
            // backgroundColor: Colors.GRAY9,
            alignItems: "center",
            justifyContent: "center",
            marginTop: RatioUtil.height(200),
        },
        emptyText: {
            fontSize: RatioUtil.font(14),
            fontWeight: "600",
            lineHeight: RatioUtil.font(14) * 1.3,
            color: Colors.GRAY8,
            marginTop: RatioUtil.height(20),
        },
    }),

    setting: StyleSheet.create({
        menuCon: {
            width: RatioUtil.width(360),
            height: RatioUtil.height(460),
            justifyContent: "space-between",
            alignItems: "center",
            paddingTop: RatioUtil.height(31),
            paddingBottom: RatioUtil.height(21),
        },
        menuText: {
            fontSize: RatioUtil.font(16),
            fontWeight: "700",
            lineHeight: RatioUtil.font(16) * 1.4,
            color: Colors.BLACK2,
        },
        imageCon: {
            width: RatioUtil.width(18),
            height: RatioUtil.width(18),
            alignItems: "center",
            justifyContent: "center",
        },
        arrowImage: { width: RatioUtil.width(7), height: RatioUtil.height(12) },
        buttonCon: {
            position: "absolute",
            bottom: 0,
            width: RatioUtil.width(58),
            height: RatioUtil.height(24),
            borderRadius: RatioUtil.width(12.5),
            backgroundColor: Colors.GRAY9,
            alignItems: "center",
            justifyContent: "center",
        },
        text: {
            fontSize: RatioUtil.font(12),
            fontWeight: "600",
            lineHeight: RatioUtil.font(12) * 1.4,
            color: Colors.GRAY3,
        },
    }),
}
export const mineCompoStyle = {
    profileButton: StyleSheet.create({
        con: {
            // width: RatioUtil.width(80),
            // height: RatioUtil.width(80),
            ...RatioUtil.size(80, 80),
            // marginRight: RatioUtil.width(20),
            ...RatioUtil.margin(0, 17),
        },
        editIcon: {
            position: "absolute",
            bottom: RatioUtil.height(-0.7),
            right: RatioUtil.width(2.24),
            // width: RatioUtil.width(22.37),
            // height: RatioUtil.height(22.19),
            ...RatioUtil.size(22.37, 22.19),
        },
    }),

    editImgPopup: StyleSheet.create({
        con: {
            // width: RatioUtil.width(360),
            // height: RatioUtil.height(204),
            ...RatioUtil.size(360, 204),
            backgroundColor: Colors.WHITE,
            // marginTop: RatioUtil.height(488),
            ...RatioUtil.margin(488),
            // borderTopStartRadius: 30,
            // borderTopEndRadius: 30,
            ...RatioUtil.padding(0, 0, 0, 20),
            ...RatioUtil.borderRadius(16, 16),
        },
        titleText: {
            fontWeight: "700",
            fontSize: RatioUtil.font(16),
            textAlign: "center",
            marginTop: RatioUtil.height(18),
            color: Colors.BLACK,
        },
        selectCon: {
            // width: RatioUtil.width(320),
            // height: RatioUtil.height(54),
            ...RatioUtil.size(320, 54),
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        selectBox: {
            flexDirection: "row",
        },
        selectBoxText: {
            fontWeight: "400",
            fontSize: RatioUtil.font(16),
            color: Colors.BLACK,
        },

        icon: {
            // width: RatioUtil.width(26),
            // height: RatioUtil.height(26),
            ...RatioUtil.size(26, 26),
            ...RatioUtil.margin(0, 20),
        },
        show: {
            width: RatioUtil.width(18),
            height: RatioUtil.height(18),
        },
        closeBox: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            position: "absolute",
            top: RatioUtil.width(18),
            right: RatioUtil.height(18),
        },
        close: {
            width: RatioUtil.width(25),
            height: RatioUtil.height(25),
        },
    }),
    photoPopup: StyleSheet.create({
        con: {
            marginTop: RatioUtil.height(44),
            // ...RatioUtil.margin(44),
            // width: RatioUtil.width(360),
            // height: RatioUtil.height(648),
            ...RatioUtil.size(360, 640),
            backgroundColor: Colors.WHITE,
            // borderTopLeftRadius: 15,
            // borderTopRightRadius: 15,
            ...RatioUtil.borderRadius(15, 15),
            ...RatioUtil.padding(18, 20, 0, 20),
        },
        header: {
            flexDirection: "row",
            width: RatioUtil.width(320),
            justifyContent: "space-between",
            ...RatioUtil.margin(0, 0, 24, 0),
        },
        headerCancel: {
            fontSize: RatioUtil.font(16),
            color: Colors.GRAY3,
        },
        headerTitle: {
            fontWeight: "700",
            fontSize: RatioUtil.font(16),
            color: Colors.BLACK,
            ...RatioUtil.padding(0, 0, 0, 2),
        },
        headerSelect: {
            fontWeight: "600",
            fontSize: RatioUtil.font(16),
            color: Colors.PURPLE,
        },
        galleryScroll: {
            width: RatioUtil.width(370),
            flexDirection: "row",
            flexWrap: "wrap",
            justifyContent: "flex-start",
        },
        galleryBox: {
            // width: RatioUtil.width(100),
            // height: RatioUtil.height(100),
            ...RatioUtil.size(100, 100),
            // backgroundColor: Colors.GRAY7,
            // marginRight: RatioUtil.width(10),
            ...RatioUtil.borderRadius(6),
            alignItems: "center",
            justifyContent: "center",
        },
        albumBox: {
            ...RatioUtil.size(100, 100),
            ...RatioUtil.borderRadius(6),
            alignItems: "center",
            justifyContent: "center",
        },
        check: {
            position: "absolute",
            right: "10%",
            top: "10%",
        },
        headerCenterCon: {
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            width: RatioUtil.width(90),
        },
        headerTab: {
            fontSize: RatioUtil.font(16),
            color: Colors.GRAY3,
            padding: 5,
            borderRadius: 5,
        },
        headerTabActive: {
            fontSize: RatioUtil.font(16),
            color: Colors.BLACK,
            paddingHorizontal: 8,
            paddingVertical: 5,
            borderRadius: 5,
            overflow: "hidden",
            backgroundColor: Colors.GRAY,
        },
    }),
    logoutModal: StyleSheet.create({
        con: {
            width: RatioUtil.width(272),
            height: RatioUtil.height(163),
            borderRadius: RatioUtil.width(16),
            backgroundColor: Colors.WHITE,
            alignItems: "center",
            justifyContent: "center",
            alignSelf: "center",
        },
        text: {
            fontSize: RatioUtil.font(18),
            fontWeight: "600",
            lineHeight: RatioUtil.font(18) * 1.5,
            color: Colors.BLACK3,
        },
        buttonCon: {
            width: RatioUtil.width(113),
            height: RatioUtil.height(48),
            alignItems: "center",
            justifyContent: "center",
            borderRadius: RatioUtil.width(24),
        },
        buttonText: {
            fontSize: RatioUtil.font(14),
            fontWeight: "600",
            lineHeight: RatioUtil.font(14) * 1.4,
        },
    }),
    editCompleteModal: StyleSheet.create({
        con: {
            // ...RatioUtil.size(144, 170),
            alignItems: "center",
            justifyContent: "center",
            borderRadius: RatioUtil.width(10),
            alignSelf: "center",
            backgroundColor: Platform.OS === "ios" ? `${Colors.BLACK}40` : `${Colors.BLACK}90`,
        },
        text: {
            fontSize: RatioUtil.font(14),
            fontWeight: "500",
            color: Colors.WHITE,
        },
    }),
    photoNftPopup: StyleSheet.create({
        menuCon: {
            ...RatioUtil.size(340, 54),
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            ...RatioUtil.margin(0, 0, 8, 0),
        },
        menuBox: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
        },
        menu: {
            borderColor: Colors.GRAY7,
            borderRadius: RatioUtil.width(6),
            borderWidth: 1,
            ...RatioUtil.padding(5, 9, 5, 9),
            minWidth: RatioUtil.width(56),
        },
        menuText: {
            color: Colors.BLACK,
            fontWeight: "700",
            fontSize: RatioUtil.font(14),
        },
    }),
}

export const mineGStyle = {
    con: {
        flex: 1,
        backgroundColor: Colors.WHITE,
    },

    menuBox: StyleSheet.create({
        con: {
            // width: RatioUtil.width(320),
            // height: RatioUtil.height(60),
            ...RatioUtil.size(320, 60),
            backgroundColor: Colors.GRAY9,
            // borderRadius: RatioUtil.width(8),
            // paddingHorizontal: RatioUtil.width(20),
            ...RatioUtil.borderRadius(8),
            ...RatioUtil.padding(0, 25, 0, 20),
            //...RatioUtil.margin(0, 0, 10, 10),
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
        },
    }),
    bgCon: { flex: 1, backgroundColor: Colors.WHITE },
    grayBar: {
        width: RatioUtil.width(320),
        height: RatioUtil.heightFixedRatio(1),
        backgroundColor: Colors.GRAY7,
    },
}
