import { combineReducers } from "@reduxjs/toolkit"
import { Platform, ScaledSize, StyleSheet } from "react-native"
import { Colors, Dimension } from "const"
import { RatioUtil } from "utils"

export const nftStyle = {
    nftCard: StyleSheet.create({
        con: {
            //flex: 0.73,
            //height: RatioUtil.height(450),
            backgroundColor: Colors.WHITE,
            // borderBottomLeftRadius: RatioUtil.lengthFixedRatio(20),
            // borderBottomRightRadius: RatioUtil.lengthFixedRatio(20),
        },
        TopBox: {
            flexDirection: "row",
            marginTop: RatioUtil.lengthFixedRatio(20),
            marginLeft: RatioUtil.lengthFixedRatio(20),
            marginRight: RatioUtil.lengthFixedRatio(15),
            width: RatioUtil.lengthFixedRatio(325),
            height: RatioUtil.lengthFixedRatio(28),
            justifyContent: "space-between",
        },
        BottomBox: {
            width: RatioUtil.lengthFixedRatio(320),
            marginBottom: RatioUtil.lengthFixedRatio(30),
        },
        seasonBox: {
            width: RatioUtil.lengthFixedRatio(120),
            height: RatioUtil.lengthFixedRatio(52),
        },
        seasonText: {
            color: Colors.WHITE,
            fontSize: RatioUtil.font(18),
            fontWeight: RatioUtil.fontWeightBold(),
            marginTop: RatioUtil.lengthFixedRatio(6),
        },
        helfbtn: {
            width: RatioUtil.lengthFixedRatio(28),
            height: RatioUtil.lengthFixedRatio(28),
            justifyContent: "center",
            alignItems: "center",
            position: "absolute",
        },
        helpbtnImg: {
            height: RatioUtil.lengthFixedRatio(12),
            width: RatioUtil.lengthFixedRatio(7),
        },
        showNameBox: {
            width: RatioUtil.lengthFixedRatio(150),
            height: RatioUtil.lengthFixedRatio(71),
            marginBottom: RatioUtil.lengthFixedRatio(20),
        },
        pointTitleBox: {
            width: RatioUtil.width(320),
            height: RatioUtil.height(80),

            backgroundColor: "rgba(255, 255, 255,0.3)",
            borderRadius: 10,
            flexDirection: "row",
            justifyContent: "center",
            alignItems: "center",
        },
        pointTitleText: {
            height: RatioUtil.lengthFixedRatio(18),
            width: RatioUtil.lengthFixedRatio(56),
            fontSize: RatioUtil.font(14),
            fontWeight: RatioUtil.fontWeightBold(),
            color: Colors.WHITE,
            textAlign: "center",
        },
        pointText: {
            height: RatioUtil.lengthFixedRatio(21),
            width: RatioUtil.lengthFixedRatio(56),
            fontSize: RatioUtil.font(16),
            marginTop: RatioUtil.lengthFixedRatio(8),
            fontWeight: RatioUtil.fontWeightBold(),
            color: Colors.WHITE,
            textAlign: "center",
        },
        pointTextBox: {
            height: RatioUtil.lengthFixedRatio(47),
            width: RatioUtil.lengthFixedRatio(56),
            justifyContent: "center",
            alignItems: "center",
        },
        lvText: {
            fontSize: RatioUtil.font(26),
            fontWeight: "600",
            lineHeight: RatioUtil.height(36.4),
            color: Colors.WHITE,
        },
        nameText: {
            fontSize: RatioUtil.font(32),
            fontWeight: RatioUtil.fontWeightBold(),
            color: Colors.WHITE,
        },
        codeText: {
            fontSize: RatioUtil.font(18),
            fontWeight: RatioUtil.fontWeightBold(),
            color: Colors.WHITE,
        },
        gradeBox: {
            width: RatioUtil.width(85),
            height: RatioUtil.height(90),
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: "rgba(255, 255, 255, 0.6)",
            borderRadius: 8,
        },
        gradeImg: { width: RatioUtil.width(32), height: RatioUtil.height(32) },
        gradeText: {
            width: RatioUtil.width(100),
            fontSize: RatioUtil.font(18),
            fontWeight: RatioUtil.fontWeightBold(),
            color: Colors.WHITE,
        },
        earnBox: {
            width: RatioUtil.lengthFixedRatio(144),
            height: RatioUtil.lengthFixedRatio(28),
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: "rgba(255, 255, 255, 0.2)",
            flexDirection: "row",
        },
        earnImg: {
            width: RatioUtil.lengthFixedRatio(16),
            height: RatioUtil.lengthFixedRatio(16),
        },
        earnText: {
            height: RatioUtil.lengthFixedRatio(18),
            fontSize: RatioUtil.font(14),
            fontWeight: "400",
            marginLeft: RatioUtil.lengthFixedRatio(6),
            marginBottom: RatioUtil.lengthFixedRatio(2),
            marginTop: Platform.OS === "ios" ? RatioUtil.lengthFixedRatio(3) : 0,
            color: Colors.WHITE,
        },
        earnPointText: {
            height: RatioUtil.lengthFixedRatio(18),
            fontSize: RatioUtil.font(14),
            fontWeight: RatioUtil.fontWeightBold(),
            color: Colors.WHITE,
            textAlign: "center",
            marginBottom: RatioUtil.lengthFixedRatio(2),
            marginTop: Platform.OS === "ios" ? RatioUtil.lengthFixedRatio(3) : 0,
        },
        nftView: {
            width: RatioUtil.lengthFixedRatio(28),
            height: RatioUtil.lengthFixedRatio(28),
            backgroundColor: "rgba(255, 255, 255, 0.2)",
            flexDirection: "row",
            justifyContent: "center",
            alignItems: "center",
        },
        nftDataView: {
            width: RatioUtil.lengthFixedRatio(320),
            height: RatioUtil.lengthFixedRatio(80),
            backgroundColor: "rgba(255, 255, 255, 0.1)",
            flexDirection: "row",
            justifyContent: "center",
            alignItems: "center",
        },
    }),
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    nftButton: StyleSheet.create({
        con: {
            flexDirection: "row",
            height: RatioUtil.lengthFixedRatio(103),
            marginLeft: RatioUtil.lengthFixedRatio(15),
            marginRight: RatioUtil.lengthFixedRatio(15),
            justifyContent: "space-around",
            alignItems: "center",
        },
        btnCon: {
            width: RatioUtil.lengthFixedRatio(95),
            height: RatioUtil.lengthFixedRatio(103),
            alignItems: "center",
        },
        btnBox: {
            width: RatioUtil.lengthFixedRatio(74),
            height: RatioUtil.lengthFixedRatio(74),
            alignItems: "center",
            justifyContent: "center",
        },
        btnBoxName: {
            fontSize: RatioUtil.font(16),
            marginTop: RatioUtil.lengthFixedRatio(8),
            fontWeight: "400",
            lineHeight: RatioUtil.lengthFixedRatio(20.8),
            color: Colors.BLACK,
        },
        levelUpbtn: {
            zIndex: 1,
            position: "absolute",
            width: RatioUtil.lengthFixedRatio(48),
            height: RatioUtil.lengthFixedRatio(48),
            borderRadius: RatioUtil.lengthFixedRatio(48),
            justifyContent: "center",
            alignItems: "center",
            top: RatioUtil.lengthFixedRatio(13),
        },
        levelUpText: {
            fontSize: RatioUtil.font(16),
            fontWeight: "700",
            color: Colors.WHITE,
        },
        walletbtn: {
            width: RatioUtil.lengthFixedRatio(74),
            height: RatioUtil.lengthFixedRatio(74),
        },
        modalbtn: {
            width: RatioUtil.width(74),
            height: RatioUtil.height(74),
            borderRadius: 100,
            position: "absolute",
            opacity: 0,
        },
    }),
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    nftModal: StyleSheet.create({
        con: {
            backgroundColor: Colors.WHITE,
            flexDirection: "column",
            alignContent: "center",
            alignItems: "center",
            position: "absolute",
            bottom: 0,
            width: RatioUtil.width(360),
            borderTopLeftRadius: RatioUtil.width(16),
            borderTopRightRadius: RatioUtil.width(16),
        },
        circlecon: {
            width: RatioUtil.width(360),
            height: RatioUtil.height(175),
            alignItems: "center",
        },

        title: {
            fontSize: RatioUtil.font(18),
            fontWeight: "700",
            marginTop: RatioUtil.height(18),
            color: Colors.BLACK,
            lineHeight: RatioUtil.height(25.2),
        },
        closebtn: {
            left: RatioUtil.width(20),
            width: RatioUtil.width(108),
            height: RatioUtil.height(60),
            backgroundColor: Colors.GRAY,
            borderRadius: RatioUtil.width(100),
            alignItems: "center",
            justifyContent: "center",
            position: "absolute",
        },
        btnText: {
            fontSize: RatioUtil.font(16),
            fontWeight: RatioUtil.fontWeightBold(),
            color: Colors.BLACK,
            lineHeight: RatioUtil.height(19.09),
        },
        confirmbtn: {
            left: RatioUtil.width(138),

            width: RatioUtil.width(202),
            height: RatioUtil.height(60),
            backgroundColor: Colors.GRAY,
            borderRadius: RatioUtil.width(100),
            alignItems: "center",
            justifyContent: "center",
            position: "absolute",
        },
        confirmbtn2: {
            left: RatioUtil.width(138),

            width: RatioUtil.width(202),
            height: RatioUtil.height(60),
            backgroundColor: Colors.BLACK4,
            borderRadius: RatioUtil.width(100),
            alignItems: "center",
            justifyContent: "center",
            position: "absolute",
        },
        titlecon: { width: RatioUtil.width(360), height: RatioUtil.height(54), alignItems: "center" },
        showNumcon: {
            width: RatioUtil.width(360),
            alignItems: "center",
            justifyContent: "center",
        },
        showNumbox: {
            width: RatioUtil.width(320),
            height: RatioUtil.height(51),
            alignItems: "center",
            justifyContent: "center",
            borderRadius: 6,
            flexDirection: "row",
        },
        btncon: {
            flexDirection: "row",
            width: RatioUtil.width(360),
            height: RatioUtil.height(98),
            alignItems: "center",
            justifyContent: "center",
        },
        showNumText: {
            position: "absolute",
            left: RatioUtil.width(20),
            fontSize: RatioUtil.font(14),
            fontWeight: "500",
            lineHeight: RatioUtil.height(22.4),
            color: Colors.BLACK,
        },
        numText: {
            fontSize: RatioUtil.font(16),
            fontWeight: "500",
            lineHeight: RatioUtil.height(22.4),
            color: Colors.BLACK,
        },
        keyboardConfirmbtn: {
            width: RatioUtil.width(360),
            height: RatioUtil.height(54),
            backgroundColor: Colors.BLACK,
            justifyContent: "center",
            alignItems: "center",
        },
        keyboardConfirmText: {
            color: Colors.WHITE,
            fontSize: RatioUtil.font(16),
            fontWeight: "500",
            lineHeight: RatioUtil.height(22.4),
        },
        playerCardcon: {
            width: RatioUtil.width(360),
            height: RatioUtil.lengthFixedRatio(239),
            justifyContent: "center",
            alignItems: "center",
        },
        playerCard: {
            width: RatioUtil.width(116),
            height: RatioUtil.height(159),
            backgroundColor: Colors.GRAY,
            borderRadius: RatioUtil.height(15),
        },
        playerLvBox: {
            width: RatioUtil.width(112),
            height: RatioUtil.lengthFixedRatio(22),
            marginTop: RatioUtil.lengthFixedRatio(12),
            flexDirection: "row",
            justifyContent: "center",
            alignItems: "center",
        },
        lvText: {
            fontSize: RatioUtil.font(16),
            fontWeight: "500",
            position: "absolute",
            lineHeight: RatioUtil.height(22.4),
            color: "#3F3F44",
        },
        lvupbtn: {
            left: RatioUtil.width(138),
            width: RatioUtil.width(202),
            height: RatioUtil.height(60),
            backgroundColor: Colors.BLACK,
            borderRadius: RatioUtil.width(100),
            alignItems: "center",
            justifyContent: "center",
            position: "absolute",
        },
        lvUpText: {
            fontSize: RatioUtil.font(16),
            fontWeight: RatioUtil.fontWeightBold(),
            color: Colors.WHITE,
            lineHeight: RatioUtil.height(19.09),
        },
    }),
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    nftAdvancementModal: StyleSheet.create({
        con: {
            flex: 1,
            alignItems: "center",
            justifyContent: "center",
            marginLeft: "auto",
            marginRight: "auto",
        },
        box: {
            backgroundColor: Colors.WHITE,
            flexDirection: "column",
            alignContent: "center",
            alignItems: "center",
            width: RatioUtil.width(290),
            height: RatioUtil.height(335),
            borderRadius: RatioUtil.width(16),
        },
        circlecon: {
            width: RatioUtil.width(300),
            height: RatioUtil.height(175),
            alignItems: "center",
        },
        title: {
            fontSize: RatioUtil.font(18),
            fontWeight: "700",
            marginTop: RatioUtil.height(18),
            color: Colors.BLACK,
            lineHeight: RatioUtil.height(25.2),
        },
        notice: {
            fontSize: RatioUtil.font(14),
            fontWeight: "400",
            marginTop: RatioUtil.height(10),
            marginBottom: RatioUtil.height(10),
            color: Colors.BLACK,
            lineHeight: RatioUtil.height(25.2),
        },
        infoBox: {
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            width: RatioUtil.width(250),
            paddingTop: RatioUtil.width(12),
            paddingBottom: RatioUtil.width(12),
            paddingLeft: RatioUtil.width(18),
            paddingRight: RatioUtil.width(18),
            borderRadius: RatioUtil.width(6),
            marginTop: RatioUtil.height(5),
            marginBottom: RatioUtil.height(5),
            borderWidth: RatioUtil.width(1),
            borderColor: "#EAEAEA",
            height: RatioUtil.height(50),
        },
        infoTitle: {
            textAlign: "right",
            fontWeight: "700",
            fontSize: RatioUtil.font(14),
            color: Colors.BLACK,
        },
        infoValue: {
            textAlign: "right",
            fontWeight: "700",
            fontSize: RatioUtil.font(16),
            color: "#5465FF",
            lineHeight: RatioUtil.font(15) * 1.3,
        },
        priceValueBox: {
            flex: 1,
            flexDirection: "row",
            justifyContent: "flex-end",
            alignItems: "center",
        },
        priceTypeImage: {
            ...RatioUtil.size(18, 18),
            marginRight: RatioUtil.width(8),
        },
        priceValue: {
            fontWeight: "700",
            fontSize: RatioUtil.font(16),
            lineHeight: RatioUtil.font(14) * 1.3,
        },
        closebtn: {
            left: RatioUtil.width(20),
            width: RatioUtil.width(108),
            height: RatioUtil.height(60),
            backgroundColor: Colors.WHITE3,
            borderRadius: RatioUtil.width(100),
            alignItems: "center",
            justifyContent: "center",
            position: "absolute",
        },
        btnText: {
            fontSize: RatioUtil.font(16),
            fontWeight: "600",
            color: Colors.BLACK,
        },
        titlecon: {
            width: RatioUtil.width(360),
            height: RatioUtil.height(54),
            alignItems: "center",
            marginTop: RatioUtil.height(20),
        },
        btncon: {
            flexDirection: "row",
            width: RatioUtil.width(290),
            height: RatioUtil.height(98),
            alignItems: "center",
            justifyContent: "center",
        },
        gradeUpbtn: {
            left: RatioUtil.width(138),
            width: RatioUtil.width(130),
            height: RatioUtil.height(60),
            backgroundColor: Colors.BLACK,
            borderRadius: RatioUtil.width(100),
            alignItems: "center",
            justifyContent: "center",
            position: "absolute",
        },
        disabledButtonStyle: {
            backgroundColor: Colors.GRAY10,
        },
        gradeUpText: {
            fontSize: RatioUtil.font(16),
            fontWeight: "600",
            color: Colors.WHITE,
        },
    }),
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const nftGStyle = {
    nft: StyleSheet.create({
        coin: {
            resizeMode: "contain",
            width: RatioUtil.width(20),
            height: RatioUtil.height(20),
        },
    }),
}
