import { Colors } from "const"
import { Platform, Dimensions, StyleSheet } from "react-native"
import { scaleSize } from "styles/minixs"
import { RatioUtil } from "utils"
const { width, height } = Dimensions.get("window")

export const playerStyle = StyleSheet.create({
    buttonMainView: {
        // backgroundColor: 'pink',
        height: scaleSize(45),
        width: scaleSize(200),
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: scaleSize(20),
    },

    buttonView: {
        flex: 0.48,
        borderRadius: scaleSize(50),
        alignItems: "center",
        justifyContent: "center",
    },
    safeAreaView: {
        flex: 1,
        backgroundColor: Colors.WHITE,
        ...(Platform.OS === "android" && { paddingTop: scaleSize(20) }),
    },
    mainView: {
        flex: 1,
        padding: scaleSize(20),
        alignItems: "center",
    },
    backButton: {
        height: scaleSize(50),
        width: scaleSize(50),
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1,
        elevation: 1,
    },
    headerView: {
        flexDirection: "row",
        height: scaleSize(50),
        alignItems: "center",
    },
    backImage: {
        height: scaleSize(15),
        width: scaleSize(15),
    },
    headerTitleView: {
        height: scaleSize(50),
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
        position: "absolute",
    },
    headerTitle: {
        fontSize: scaleSize(15),
        lineHeight: scaleSize(19),
        fontWeight: "800",
    },
    rectangleCard: {
        height: scaleSize(140),
        width: scaleSize(95),
        borderRadius: scaleSize(5),
        marginHorizontal: scaleSize(10),
    },
    rectangleCardBox: {
        flexDirection: "row",
    },
    addRectangleCard: {
        borderWidth: 2,
        borderStyle: "dotted",
        borderColor: Colors.GRAY12,
        justifyContent: "center",
        alignItems: "center",
    },
    plus: {
        fontSize: scaleSize(30),
        color: Colors.GRAY12,
    },
    playerSelectionText: {
        fontSize: scaleSize(17),
        color: Colors.GRAY12,
        marginTop: scaleSize(5),
    },
    NFTChoiceCardTitle: {
        fontSize: scaleSize(18.5),
        color: Colors.BLACK,
        marginTop: scaleSize(25),
        fontWeight: "600",
    },
    ratingsTitle: {
        fontSize: scaleSize(13),
        lineHeight: scaleSize(15),
        color: Colors.GRAY8,
    },
    amountMainBox: {
        width: "100%",
        backgroundColor: Colors.WHITE3,
        padding: 20,
        borderRadius: scaleSize(10),
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginTop: scaleSize(80),
    },
    amountBox: {
        flexDirection: "row",
        alignItems: "center",
    },
    amount: {
        color: Colors.BLACK,
        fontSize: scaleSize(20),
        fontWeight: "600",
    },
    coinIcon: {
        height: scaleSize(20),
        width: scaleSize(20),
        marginRight: scaleSize(5),
    },
    policyMainBox: {
        width: "100%",
        alignItems: "center",
        flexDirection: "row",
        paddingHorizontal: scaleSize(10),
        marginTop: scaleSize(10),
    },
    policy: {
        fontSize: scaleSize(15.5),
        fontWeight: "600",
    },
    policyImage: {
        height: scaleSize(25),
        width: scaleSize(25),
    },
    policyBox: {
        flex: 1,
        alignItems: "flex-end",
    },
    purchaseButton: {
        padding: scaleSize(20),
        width: "100%",
        borderRadius: scaleSize(50),
        justifyContent: "center",
        marginTop: scaleSize(25),
    },
    purchaseButtonTitle: {
        textAlign: "center",
        fontSize: scaleSize(15),
    },
    checkbox: {
        borderRadius: scaleSize(20),
        marginRight: scaleSize(5),
    },
    centeredView: {
        backgroundColor: Colors.WHITE,
        width: width,
        borderTopEndRadius: scaleSize(20),
        borderTopStartRadius: scaleSize(20),
        padding: scaleSize(20),
        paddingBottom: scaleSize(150),
    },
    modalView: {
        backgroundColor: Colors.GRAY,
        flex: 1,
    },
    playerSelectionTitle: {
        fontSize: scaleSize(18.5),
        color: Colors.BLACK,
        fontWeight: "600",
        textAlign: "center",
    },
    playerSelectionDescription: {
        fontSize: scaleSize(16),
        color: Colors.GRAY8,
        fontWeight: "600",
        textAlign: "center",
        marginTop: scaleSize(10),
    },
    backgroundStyle: {
        backgroundColor: Colors.WHITE,
        borderRadius: scaleSize(10),
        flexDirection: "row",
        paddingHorizontal: 15,
        width: "100%",
        alignSelf: "flex-start",
        padding: scaleSize(20),
        borderWidth: scaleSize(1),
        borderColor: Colors.GRAY7,
        marginTop: scaleSize(20),
    },
    inputStyle: {
        fontSize: 16,
        flex: 1,
        paddingLeft: 5,
    },
    iconStyle: {
        alignSelf: "center",
        height: scaleSize(20),
        width: scaleSize(20),
        marginRight: scaleSize(5),
    },
    imageBox: {
        flex: 1,
        marginVertical: scaleSize(20),
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
    },
    image: {
        width: width / 3 - 20,
        height: scaleSize(150),
        backgroundColor: Colors.GRAY7,
        marginVertical: 5,
        borderRadius: scaleSize(10),
    },
    playerImage: {
        flex: 1,
    },
    outSideButton: {
        height: scaleSize(50),
    },
    button: {
        width: "90%",
        padding: scaleSize(20),
        borderRadius: scaleSize(30),
        position: "absolute",
        bottom: scaleSize(30),
        zIndex: 100,
        alignSelf: "center",
        alignItems: "center",
    },
    selectionModal: {
        flex: 1,
        backgroundColor: `${Colors.BLACK}70`,
        alignItems: "center",
        justifyContent: "center",
    },
    selectionModalTutorial: {
        flex: 1,
        backgroundColor: `${Colors.BLACK}60`,
        alignItems: "center",
        justifyContent: "center",
    },
    selectionModalInner: {
        backgroundColor: Colors.WHITE,
        alignItems: "center",
        padding: scaleSize(20),
        borderRadius: scaleSize(15),
        width: scaleSize(272),
        height: scaleSize(163),
    },
    selectionModalBody: {
        alignItems: "center",
        justifyContent: "center",
        padding: scaleSize(10),
    },
    selectionModalheader: {
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: scaleSize(15),
        paddingVertical: scaleSize(0),
        width: scaleSize(230),
        borderRadius: scaleSize(15),
        borderBottomColor: Colors.WHITE3,
        borderBottomWidth: 1,
    },
    selectionModalInnerTitle: {
        fontSize: scaleSize(15),
        lineHeight: scaleSize(18),
        fontWeight: "800",
        color: Colors.BLACK,
        marginBottom: scaleSize(15),
    },
    selectionModalInnerDesc: {
        fontSize: scaleSize(11),
        lineHeight: scaleSize(13),
        fontWeight: "500",
        color: Colors.BLACK,
        marginTop: scaleSize(15),
        marginBottom: scaleSize(5),
    },
    drawModalMainView: {
        // backgroundColor: 'pink'
        alignItems: "center",
    },
    drawModalInnerView: {
        height: scaleSize(35),
        width: scaleSize(200),
        flexDirection: "row",
        marginTop: scaleSize(4),
        alignItems: "center",
        justifyContent: "space-between",
        borderRadius: scaleSize(5),
        paddingHorizontal: scaleSize(15),
    },
    drawtitle: {
        fontSize: scaleSize(11),
        lineHeight: scaleSize(13),
        fontWeight: "500",
        color: Colors.BLACK,
    },
    drawProgressLeft: {
        fontSize: scaleSize(11),
        lineHeight: scaleSize(13),
        fontWeight: "700",
        color: Colors.BLACK2,
    },
    drawProgressRight: {
        fontSize: scaleSize(11),
        lineHeight: scaleSize(13),
        fontWeight: "700",
        color: Colors.WHITE,
    },
    drawProgress: {
        fontSize: scaleSize(11),
        lineHeight: scaleSize(13),
        fontWeight: "700",
        color: Colors.BLACK,
    },
    modalButtonView: {
        height: scaleSize(40),
        width: "40%",
        backgroundColor: Colors.BLACK,
        borderRadius: scaleSize(50),
        alignItems: "center",
        justifyContent: "center",
        marginTop: scaleSize(20),
    },
    modalButtonText: {
        fontSize: scaleSize(11),
        lineHeight: scaleSize(13),
        fontWeight: "700",
        color: Colors.WHITE,
    },
    selectedImage: {
        height: scaleSize(45),
        width: scaleSize(45),
    },
    completeTitle: {
        color: Colors.BLACK,
        fontSize: RatioUtil.font(14),
        textAlign: "center",
        fontWeight: "700",
    },
    completeDesc: {
        fontSize: scaleSize(12),
        lineHeight: scaleSize(14),
        color: Colors.BLACK,
        textAlign: "center",
        width: scaleSize(150),
    },
    typeModal: {
        height: scaleSize(40),
        width: "100%",
        backgroundColor: Colors.BLACK,
        marginTop: scaleSize(10),
        borderRadius: scaleSize(5),
        alignItems: "center",
        justifyContent: "center",
    },
    typeModalText: {
        fontSize: scaleSize(12),
        lineHeight: scaleSize(14),
        fontWeight: "700",
        color: Colors.WHITE,
    },
})
