import { PixelRatio, StyleSheet } from "react-native"
import { Colors, Dimension } from "const"
import { RatioUtil } from "utils"

export const walletStyle = {
    header: StyleSheet.create({
        modalMainView: {
            flex: 1,
            backgroundColor: `${Colors.BLACK}99`,
            alignItems: "center",
            justifyContent: "center",
        },
        shadowMainView: {
            borderWidth: 1,
            borderColor: Colors.GRAY13,
            ...RatioUtil.borderRadius(10),
            width: RatioUtil.width(320),
        },
        con: {
            height: RatioUtil.height(44),
            flexDirection: "row",
            backgroundColor: Colors.WHITE,
            alignItems: "center",
            justifyContent: "center",
        },
        text: {
            fontSize: RatioUtil.font(18),
            fontWeight: "600",
            lineHeight: RatioUtil.font(18) * 1.4,
            color: Colors.BLACK,
        },
        textConWhite: { fontWeight: "600", color: Colors.WHITE },
        textConBlack: { fontWeight: "600", color: Colors.BLACK },
        center: {
            alignItems: "center",
            justifyContent: "center",
        },
        row: {
            flexDirection: "row",
        },
        rowCenter: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
        },
        buttonFrom: {
            ...RatioUtil.size(158, 70),
            ...RatioUtil.borderRadius(10, 1, 1, 10),
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: Colors.PURPLE,
        },
        viewBtn: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            backgroundColor: Colors.WHITE,
            ...RatioUtil.padding(0, 20, 0, 20),
            ...RatioUtil.size(360, 90),
        },
        buttonTo: {
            ...RatioUtil.size(158, 70),
            ...RatioUtil.borderRadius(1, 10, 10, 1),
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: Colors.PURPLE,
        },
        buttonSwitch: {
            ...RatioUtil.size(60, 40),
            ...RatioUtil.borderRadius(100),
            backgroundColor: Colors.WHITE,
            elevation: 6,
            position: "absolute",
            alignSelf: "center",
            justifyContent: "center",
            alignItems: "center",
            marginTop: RatioUtil.heightFixedRatio(10)
        },
        selectButton: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            ...RatioUtil.borderRadius(8),
            ...RatioUtil.paddingFixedRatio(0, 10, 0, 10),
            borderColor: Colors.GRAY13,
            height: RatioUtil.heightFixedRatio(48),
            marginTop: RatioUtil.heightFixedRatio(10),
            borderWidth: 1.5,
        },
        buttonAll: {
            ...RatioUtil.size(42, 25),
            ...RatioUtil.borderRadius(50),
            backgroundColor: Colors.BLACK,
            alignItems: "center",
            justifyContent: "center",
        },
        buttonTransfer: {
            ...RatioUtil.size(320, 55),
            ...RatioUtil.borderRadius(100),
            ...RatioUtil.padding(0, 20, 0, 20),
            backgroundColor: Colors.WHITE3,
            justifyContent: "center",
            alignItems: "center",
        },
        bottomSheetCon: {
            backgroundColor: "#fff",
            ...RatioUtil.borderRadius(10, 10, 0, 0),
            height: RatioUtil.height(140),
            alignItems: "center",
        },
        titleBTS: {
            textAlign: "center",
            ...RatioUtil.padding(10, 0, 20, 0),
            fontSize: RatioUtil.font(18),
            color: Colors.BLACK,
            fontWeight: "600",
        },
        buttonValue: {
            ...RatioUtil.size(360, 55),
            ...RatioUtil.padding(0, 20, 0, 20),
            // backgroundColor: Colors.WHITE3,
            justifyContent: "center",
        },
        viewText: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginTop: RatioUtil.height(120),
            alignSelf: "center",
            width: "75%",
        },
    }),
    selectPlayer: StyleSheet.create({
        buttonAll: {
            alignItems: "center",
            justifyContent: "center",
            borderWidth: 1.5,
            borderColor: Colors.WHITE3,
            ...RatioUtil.size(55, 30),
            ...RatioUtil.borderRadius(6),
            ...RatioUtil.margin(0, 5, 0, 0),
        },
        buttonGrow: {
            alignItems: "center",
            justifyContent: "center",
            ...RatioUtil.size(70, 30),
            ...RatioUtil.borderRadius(6),
            borderWidth: 1.5,
            borderColor: Colors.WHITE3,
        },
        filterView: {
            ...RatioUtil.size(360, 45),
            ...RatioUtil.padding(0, 10, 0, 20),
            justifyContent: "space-between",
            alignItems: "center",
            flexDirection: "row",
        },
        con: {
            ...RatioUtil.size(360, 30),
            ...RatioUtil.padding(0, 10, 0, 15),
            justifyContent: "space-between",
            alignItems: "center",
            flexDirection: "row",
        },
        buttonSort: {
            alignItems: "center",
            justifyContent: "center",
            ...RatioUtil.padding(0, 5, 0, 0),
            ...RatioUtil.borderRadius(6),
        },
        item: {
            ...RatioUtil.size(155, 225),
            ...RatioUtil.borderRadius(20),
            ...RatioUtil.margin(5, 5, 5, 5),
            backgroundColor: Colors.PURPLE8,
            alignItems: "center",
            borderColor: Colors.PURPLE4,
            borderWidth: 2,
        },
        rowFooter: {
            flexDirection: "row",
            justifyContent: "space-between",
            ...RatioUtil.margin(5, 0, 0, 0),
            ...RatioUtil.size(130, 15),
        },
        checkedImg: {
            position: "absolute",
            right: 10,
            top: 10,
            ...RatioUtil.size(20, 20),
        },
    }),
    popUp: StyleSheet.create({
        buttonCon: {
            ...RatioUtil.padding(15, 15, 15, 15),
            ...RatioUtil.margin(0, 0, 10, 0),
            ...RatioUtil.size(340, 70),
            flexDirection: "row",
            justifyContent: "space-between",
        },
        textUnder: {
            bottom: 4,
            fontSize: RatioUtil.font(12),
            fontWeight: "600",
            color: Colors.GRAY3,
        },
        buttonHelp: {
            backgroundColor: Colors.GRAY,
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
        },
        textHeader: {
            ...RatioUtil.size(280, 500),
            backgroundColor: Colors.WHITE,
            alignItems: "center",
            justifyContent: "center",
            ...RatioUtil.borderRadius(20, 20, 20, 20),
        },
        con: {
            ...RatioUtil.size(240, 160),
            backgroundColor: Colors.WHITE3,
            justifyContent: "center",
            borderRadius: 10,
            ...RatioUtil.margin(10, 0, 10, 0),
            ...RatioUtil.padding(10, 10, 10, 10),
        },
        rowBetween: {
            flexDirection: "row",
            justifyContent: "space-between",
            ...RatioUtil.margin(5, 0, 5, 0),
        },
        totalValue: {
            ...RatioUtil.size(240, 50),
            backgroundColor: Colors.WHITE3,
            justifyContent: "center",
            borderRadius: 10,
            ...RatioUtil.padding(0, 10, 0, 10),
        },
        buttonSubmit: {
            alignItems: "center",
            justifyContent: "center",
            ...RatioUtil.padding(0, 15, 0, 15),
            ...RatioUtil.margin(25, 0, 0, 0),
            backgroundColor: Colors.BLACK,
            borderRadius: 50,
            ...RatioUtil.size(240, 50),
        },
        helpView: {
            flex: 1,
            backgroundColor: `${Colors.BLACK}50`,
            alignItems: "center",
            justifyContent: "flex-end",
        },
        helpViewColor: {
            ...RatioUtil.size(360, 620),
            // ...RatioUtil.padding(0, 20, 0, 20),
            borderTopLeftRadius: 15,
            borderTopRightRadius: 15,
            alignItems: "center",
            backgroundColor: Colors.WHITE,
        },
        helpBody: {
            ...RatioUtil.size(320, 525),
            ...RatioUtil.padding(20, 10, 20, 10),
            ...RatioUtil.borderRadius(10),
            borderColor: Colors.GRAY7,
            borderWidth: 1,
        },
        helpName: {
            fontSize: RatioUtil.font(16),
            color: Colors.BLACK,
            fontWeight: "700",
            paddingBottom: RatioUtil.height(5),
        },
        helpDetail: {
            fontSize: RatioUtil.font(14),
            color: Colors.GRAY8,
            fontWeight: "500",
        },
    }),
    detailMain: StyleSheet.create({
        tab: {
            ...RatioUtil.borderRadius(20, 20, 20, 20),
            ...RatioUtil.size(62, 35),
            borderWidth: 1.5,
            borderColor: Colors.GRAY13,
            alignItems: "center",
            justifyContent: "center",
        },
        header1: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            ...RatioUtil.size(320, 50),
        },
        header2: {
            ...RatioUtil.size(90, 50),
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
        },
    }),
    passionate: StyleSheet.create({
        textOpacity: {
            fontSize: RatioUtil.font(14),
            opacity: 0.5,
        },
        header1: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            ...RatioUtil.size(320, 50),
        },
        header2: {
            ...RatioUtil.size(90, 50),
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
        },
        textName: {
            fontWeight: "600",
            color: Colors.WHITE,
            fontSize: RatioUtil.font(20),
            ...RatioUtil.margin(5, 0, 5, 0),
        },
        textCount: {
            fontWeight: "600",
            color: Colors.WHITE,
            fontSize: RatioUtil.font(14),
            opacity: 0.5,
        },
        positionView: {
            position: "absolute",
            bottom: RatioUtil.height(10),
            marginHorizontal: RatioUtil.width(10),
        },
    }),

    listItem: StyleSheet.create({
        container: {
            ...RatioUtil.margin(10, 10, 10, 10),
            ...RatioUtil.padding(10, 10, 10, 10),
        },
        spendingListItem: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            ...RatioUtil.margin(10, 0, 0, 0),
            // ...RatioUtil.padding(0, 20, 0, 15),
        },
        spendingTextScore: {
            alignItems: "flex-end",
            justifyContent: "center",
            ...RatioUtil.size(140, 25),
        },
        transactionHistoryListItem: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            ...RatioUtil.margin(5, 0, 5, 0),
            height: RatioUtil.height(50),
        },
        textBold: { fontWeight: "700", color: Colors.BLACK },
        textScore: {
            alignItems: "flex-end",
            justifyContent: "center",
            ...RatioUtil.size(100, 45),
        },
        buttonDetail: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            borderBottomColor: Colors.WHITE3,
            borderBottomWidth: 1,
            ...RatioUtil.padding(10, 0, 10, 0),
        },
        userAvatar: {
            backgroundColor: Colors.WHITE,
            ...RatioUtil.size(39, 39),
            justifyContent: "center",
            alignSelf: "center",
            borderRadius: 50,
        },
        buttonDetailFooter: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            height: RatioUtil.height(55),
            ...RatioUtil.borderRadius(0, 0, 10, 10),
            // ...RatioUtil.size(318, 50),
        },
        myRankTextCon: {
            alignItems: "center",
            justifyContent: "center",
            borderRightColor: Colors.GRAY,
            paddingRight: 10,
            borderRightWidth: 1.5,
        },
        textRank: {
            fontWeight: "600",
            color: Colors.BLACK,
            fontSize: RatioUtil.font(14),
            marginHorizontal: RatioUtil.width(10),
            paddingRight: RatioUtil.width(20),
        },
        imageMyRank: {
            ...RatioUtil.size(15, 15),
            marginRight: RatioUtil.width(4),
            borderRadius: 50,
        },
    }),

    footer: StyleSheet.create({
        walletRight: {
            ...RatioUtil.size(20, 20),
            alignSelf: "center",
            ...RatioUtil.padding(0, 15, 0, 15),
        },
    }),
    compo: StyleSheet.create({
        container: {
            ...RatioUtil.margin(10, 10, 10, 10),
            ...RatioUtil.padding(10, 10, 10, 10),
        },
        walletAdd: {
            ...RatioUtil.size(280, 40),
            ...RatioUtil.borderRadius(10),
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: Colors.WHITE3,
        },
        buttonDetail: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            ...RatioUtil.padding(10, 0, 15, 0),
        },
        listIcon: {
            width: RatioUtil.width(320),
            ...RatioUtil.padding(15, 0, 15, 0),
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
        },
        icon: {
            width: RatioUtil.width(70),
        },
    }),
}

export const walletTabStyle = {
    header: StyleSheet.create({
        mainView: {
            flex: 1,
            // paddingTop: scaleSize(10),
            alignItems: "center",
        },
    }),
    popup: StyleSheet.create({
        title: {
            fontWeight: "600",
            fontSize: RatioUtil.font(18),
            color: Colors.BLACK,
        },
        center: {
            alignItems: "center",
            justifyContent: "center",
        },
        viewRow: {
            ...RatioUtil.size(360, 170),
            padding: RatioUtil.width(20),
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
        },
        container: {
            height: RatioUtil.height(110),
            borderRadius: RatioUtil.width(10),
            backgroundColor: Colors.GRAY9,
            overflow: "hidden",
        },
        txtUserName: {
            ...RatioUtil.padding(0, 0, 10, 0),
            flex: 1,
            alignItems: "center",
            justifyContent: "flex-end",
        },
        icon: {
            position: "absolute",
            top: -RatioUtil.width(10),
            left: RatioUtil.width(32),
            ...RatioUtil.size(33, 33),
        },
    }),
}
